<a href="https://colab.research.google.com/github/reechakumari/Python_Code/blob/master/Discrete_Hopfield_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np
x=np.array([[1,1,1,1,1],[1,-1,-1,1,-1],[-1,1,-1,-1,-1]])

print("x matrix:")
print(x)
x1=np.transpose(x)
print("\nx1 is the transpose matrix of matrix x:")
print(x1)

w=np.zeros((5,5))
print("\nW matrix initially: ")
print(w)

i=0
j=0
k=0
for i in range(len(x1)):
  for j in range(len(x[0])):
    for k in range(len(x)):
      w[i][j] += x1[i][k] * x[k][j]

print('\nWeight Matrix:')
for r in w:
  print(r)

print('\nWeight Matrix with no self connection:')
i=0
j=0
for i in range(int(5)):
  for j in range(int(5)):
    if(i==j):
      w[i][j]=0

for r in w:
  print(r)

x matrix:
[[ 1  1  1  1  1]
 [ 1 -1 -1  1 -1]
 [-1  1 -1 -1 -1]]

x1 is the transpose matrix of matrix x:
[[ 1  1 -1]
 [ 1 -1  1]
 [ 1 -1 -1]
 [ 1  1 -1]
 [ 1 -1 -1]]

W matrix initially: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Weight Matrix:
[ 3. -1.  1.  3.  1.]
[-1.  3.  1. -1.  1.]
[1. 1. 3. 1. 3.]
[ 3. -1.  1.  3.  1.]
[1. 1. 3. 1. 3.]

Weight Matrix with no self connection:
[ 0. -1.  1.  3.  1.]
[-1.  0.  1. -1.  1.]
[1. 1. 0. 1. 3.]
[ 3. -1.  1.  0.  1.]
[1. 1. 3. 1. 0.]


In [74]:
E1=0
E2=0
E3=0
x11= x[0].reshape(5,1)
x12=x[1].reshape(5,1)
x13=x[2].reshape(5,1)
print("\nReshape of x[0]:")
print(x11)
print("\nReshape of x[1]:")
print(x12)
print("\nReshape of x[2]:")
print(x13)

E1= -0.5 * np.matmul(x[0],np.matmul(w,x11))
print('\nEnergy Calculations for pattern [1,1,1,1,1]:',E1)

E2= -0.5 * np.matmul(x[1],np.matmul(w,x12))
print('\nEnergy Calculations for pattern [1,-1,-1,1,-1]:',E2)

E3= -0.5 * np.matmul(x[2],np.matmul(w,x13))
print('\nEnergy Calculations for pattern [-1,1,-1,1,-1]:',E3)


Reshape of x[0]:
[[1]
 [1]
 [1]
 [1]
 [1]]

Reshape of x[1]:
[[ 1]
 [-1]
 [-1]
 [ 1]
 [-1]]

Reshape of x[2]:
[[-1]
 [ 1]
 [-1]
 [-1]
 [-1]]

Energy Calculations for pattern [1,1,1,1,1]: [-10.]

Energy Calculations for pattern [1,-1,-1,1,-1]: [-6.]

Energy Calculations for pattern [-1,1,-1,1,-1]: [-10.]


In [75]:
print('\n\nTESTING PHASE')
t1=np.array([[1,1,1,-1,1]])
t2=np.array([[1,-1,-1,-1,-1]])
t3=np.array([[1,1,-1,-1,-1]])

print("\nt1 matrix:",t1)
print("\nt2 matrix:",t2)
print("\nt3 matrix:",t3)



TESTING PHASE

t1 matrix: [[ 1  1  1 -1  1]]

t2 matrix: [[ 1 -1 -1 -1 -1]]

t3 matrix: [[ 1  1 -1 -1 -1]]


In [76]:
w_Trans=np.transpose(w)
print(w_Trans)


[[ 0. -1.  1.  3.  1.]
 [-1.  0.  1. -1.  1.]
 [ 1.  1.  0.  1.  3.]
 [ 3. -1.  1.  0.  1.]
 [ 1.  1.  3.  1.  0.]]


In [77]:
print(t1)

[[ 1  1  1 -1  1]]


In [78]:
print(x)

[[ 1  1  1  1  1]
 [ 1 -1 -1  1 -1]
 [-1  1 -1 -1 -1]]


In [81]:
Y_t1=t1[0][3]+ np.matmul(x[0],w_Trans[3])
if(Y_t1>0):
  t1[0][3]=1
else:
  t1[0][3]=-1

if((t1==x).any()):
  print('\nPattern [1,1,1,-1,1] Recognized ')
else:
  print('\nPattern [1,1,1,-1,1] not Recognized ')


Pattern [1,1,1,-1,1] Recognized 


In [82]:
print(t1)

[[1 1 1 1 1]]


In [87]:
print(t2)

[[ 1 -1 -1 -1 -1]]


In [88]:
print(x)

[[ 1  1  1  1  1]
 [ 1 -1 -1  1 -1]
 [-1  1 -1 -1 -1]]


In [90]:
Y_t2=t2[0][3]+ np.matmul(x[1],w_Trans[3])
if(Y_t2>0):
  t2[0][3]=1
else:
  t2[0][3]=-1

if((t2==x).any()):
  print('\nPattern [1,-1,-1,-1,-1] Recognized ')
else:
  print('\nPattern [1,-1,-1,-1,-1] not Recognized ')


Pattern [1,-1,-1,-1,-1] Recognized 


In [91]:
print(t2)

[[ 1 -1 -1  1 -1]]


In [95]:
print(t3)

[[-1  1 -1 -1 -1]]


In [96]:
print(x)

[[ 1  1  1  1  1]
 [ 1 -1 -1  1 -1]
 [-1  1 -1 -1 -1]]


In [101]:
Y_t3=t3[0][0]+ np.matmul(x[2],w_Trans[0])
if(Y_t3>0):
  t3[0][0]=1
else:
  t3[0][0]=-1

if((t3==x).any()):
  print('\nPattern [1,1,-1,-1,-1] Recognized ')
else:
  print('\nPattern [1,1,-1,-1,-1] not Recognized ')


Pattern [1,1,-1,-1,-1] Recognized 


In [104]:
print(t3)

[[-1  1 -1 -1 -1]]
