<a href="https://colab.research.google.com/github/reechakumari/Python_Code/blob/master/image_color_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
a = numpy.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(3,)

In [ ]:
b = numpy.zeros( [100,20,3], dtype=numpy.uint8 )

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(100, 20, 3)

In [ ]:
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [ ]:
cv2.imshow('hi', b)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
import cv2

In [ ]:
cap  = cv2.VideoCapture(0)

In [ ]:
ret, photo = cap.read()

In [ ]:
ret

True

In [ ]:
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
cap.release()

In [ ]:
type(photo)

numpy.ndarray

In [ ]:
photo.shape

(480, 640, 3)

In [ ]:
photo[0][0] = [26,0,0]

In [ ]:
photo

array([[[ 26,   0,   0],
        [ 27,  32,  30],
        [ 27,  32,  30],
        ...,
        [ 35,  37,  38],
        [ 36,  35,  37],
        [ 35,  34,  36]],

       [[ 26,  31,  29],
        [ 27,  32,  30],
        [ 27,  32,  30],
        ...,
        [ 36,  38,  39],
        [ 35,  37,  38],
        [ 33,  35,  36]],

       [[ 26,  31,  29],
        [ 27,  32,  30],
        [ 27,  32,  30],
        ...,
        [ 35,  39,  40],
        [ 34,  38,  39],
        [ 32,  36,  37]],

       ...,

       [[121, 138, 129],
        [114, 133, 124],
        [107, 126, 117],
        ...,
        [ 20,  24,  19],
        [ 20,  24,  19],
        [ 21,  25,  20]],

       [[129, 162, 147],
        [123, 156, 141],
        [115, 148, 134],
        ...,
        [ 19,  23,  18],
        [ 20,  24,  19],
        [ 21,  25,  20]],

       [[123, 165, 147],
        [124, 166, 148],
        [127, 166, 150],
        ...,
        [ 19,  23,  18],
        [ 21,  25,  20],
        [ 21,  25,  20]]

In [ ]:
b , g , r = cv2.split(photo)

In [ ]:
newphoto = cv2.merge( [b , g , r] )

In [ ]:
cv2.imshow('hi', newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
b , g , r = cv2.split(photo)

In [ ]:
r.shape

(480, 640)

In [ ]:
myzeros =  numpy.zeros([480, 640], dtype=numpy.uint8)

In [ ]:
red_image = cv2.merge([myzeros , myzeros, r ])

In [ ]:
cv2.imshow('hi', red_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
blue_image = cv2.merge([b , myzeros , myzeros])

In [ ]:
cv2.imshow('hi', blue_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
cap.release()